### ISSUE TITLE
Idea: Disable spawning of new corrupt/crimson blocks when breaking altars

### ISSUE THREAD

**Issue by Sparrows413** [JavidPack/DisableCorruptionSpread#2]
I'd like to be able to leave corruption spreading turned on, but I don't like the idea of busting open altars and getting a nasty surprise further on down the road when it turns out it dropped corruption into the middle of my jungle that I didn't know about.

Could it be made an option at some point to disable the spawning of corrupt/crimson blocks when an altar is broken, ideally without also having to turn off corruption spreading as a whole?

**Comment by JavidPack** [comment]
Sounds like a good suggestion, I'll see what I can do.
